/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package info.maila.filedialogs

import javafx.application.Platform
import javafx.stage.FileChooser
import java.awt.FileDialog
import java.awt.Frame
import java.awt.event.ActionEvent
import javax.swing.*


fun main() {

    with(JFrame("File Dialogs")) {
        defaultCloseOperation = WindowConstants.EXIT_ON_CLOSE
        layout = BoxLayout(contentPane, BoxLayout.PAGE_AXIS)
        add(createButton("JFileChooser") { JFileChooser().showOpenDialog(null) })
        add(createButton("FileDialog") { FileDialog(null as Frame?).isVisible = true })
        add(createButton("FileChooser") { showFileChooser() })
        pack()
        setLocationRelativeTo(null)
        isVisible = true
    }

}

fun createButton(label: String, block: () -> Unit) =
    JButton().apply {
        action = object : AbstractAction(label) {
            override fun actionPerformed(e: ActionEvent?) {
                block()
            }
        }
    }

val jfxStartup by lazy { Platform.startup { } }

fun showFileChooser() {
    val startup = jfxStartup
    Platform.runLater {
        FileChooser().showOpenDialog(null)
    }
}